image: "python:2.7"

variables:
  ODOO_VERSION: "10.0"
  ODOO_MODULES: "base"

stages:
  - test

flake8:
  tags:
    - flake8
  stage: test
  script:
  - flake8 --config=.flakerc .

tests:
  tags:
    - odoo
  stage: test
  script:
  - dropdb --if-exists $CI_BUILD_REF
  - virtualenv env
  - source env/bin/activate
  - pip install -r requirements.txt
  - git clone --quiet --depth=1 --branch=$ODOO_VERSION https://github.com/odoo/odoo.git env/odoo
  - rm -rf env/odoo/.git
  - pip install -q -r env/odoo/requirements.txt
  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 -D ramdisk $CI_BUILD_REF
  - ./env/odoo/odoo.py -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./ --log-level=warn --stop-after-init
  - ./env/odoo/odoo.py -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./ -i $ODOO_MODULES --without-demo=all --log-level=warn --stop-after-init
  - ./env/odoo/odoo.py -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./ -i $ODOO_MODULES --test-enable --log-level=warn --stop-after-init
  - dropdb --if-exists $CI_BUILD_REF
